export interface MapPinPoint {
  id: string;
  name: string;
  category: 'restaurant' | 'attraction' | 'theatre' | 'transit' | 'hotel' | 'park';
  lat: number;
  lng: number;
  address: string;
  rating?: number;
  highlight: string;
  actionText: string;
  actionUrl: string;
  hours?: string;
  priceLevel?: string;
}

export interface GeoSpotlightDistrict {
  id: string;
  tenantId: string;
  keywords: string[];
  name: string;
  tagline: string;
  center: [number, number]; // [lat, lng]
  zoom: number;
  description: string;
  vibe: string;
  walkScore: number;
  transitAccess: string;
  pins: MapPinPoint[];
}

export const CANADIAN_GEO_SPOTLIGHTS: GeoSpotlightDistrict[] = [
  // ================= CALGARY (YYC) =================
  {
    id: 'yyc-stephen-ave',
    tenantId: 'yyc',
    keywords: ['stephen ave', 'stephen avenue', '8th ave', 'downtown calgary', 'stephen'],
    name: 'Stephen Avenue Walk',
    tagline: 'Calgary\'s Historic Heritage Pedestrian Mall',
    center: [51.0458, -114.0680],
    zoom: 16,
    description: 'Bustling pedestrian promenade lined with sandstone heritage architecture, award-winning steakhouses, lively patios, and street buskers.',
    vibe: 'Sophisticated Dining, Heritage Cocktails & Live Music',
    walkScore: 98,
    transitAccess: '1st St SW & Centre St C-Train Stations (Free Fare Zone)',
    pins: [
      {
        id: 'major-tom',
        name: 'Major Tom Bar',
        category: 'restaurant',
        lat: 51.0455,
        lng: -114.0689,
        address: '40th Floor, 700 2 St SW',
        rating: 4.9,
        highlight: '40-Floor Skyview • Dry-Aged Alberta Prime Rib • Vintage Cocktails',
        actionText: 'Book Table on SevenRooms',
        actionUrl: 'https://sevenrooms.com/reservations/majortombar',
        hours: '5:00 PM - 11:00 PM Daily',
        priceLevel: '$$$$',
      },
      {
        id: 'teatro',
        name: 'Teatro Ristorante',
        category: 'restaurant',
        lat: 51.0459,
        lng: -114.0601,
        address: '200 8 Ave SE (Olympic Plaza)',
        rating: 4.8,
        highlight: 'Classic Mediterranean Fine Dining in 1911 Dominion Bank',
        actionText: 'Reserve on OpenTable',
        actionUrl: 'https://opentable.com/teatro',
        hours: '5:00 PM - 10:00 PM',
        priceLevel: '$$$$',
      },
      {
        id: 'charcut',
        name: 'Charcut Roast House',
        category: 'restaurant',
        lat: 51.0461,
        lng: -114.0628,
        address: '899 Centre St S',
        rating: 4.7,
        highlight: 'Butcher-driven Rotisserie & House-cured Charcuterie',
        actionText: 'Book Table on OpenTable',
        actionUrl: 'https://opentable.com/charcut',
        hours: '11:30 AM - 10:00 PM',
        priceLevel: '$$$',
      },
      {
        id: 'glenbow',
        name: 'Glenbow Museum & Art Gallery',
        category: 'attraction',
        lat: 51.0449,
        lng: -114.0608,
        address: '130 9 Ave SE',
        highlight: 'Western Canada\'s Largest Arts & Culture Collection',
        actionText: 'Get Museum Passes',
        actionUrl: 'https://glenbow.org',
        hours: '10:00 AM - 5:00 PM',
      },
      {
        id: 'olympic-plaza',
        name: 'Olympic Plaza',
        category: 'park',
        lat: 51.0460,
        lng: -114.0592,
        address: '228 8 Ave SE',
        highlight: '1988 Olympic Medal Site • Winter Skating & Summer Stage',
        actionText: 'View Plaza Events',
        actionUrl: 'https://calgary.ca/olympicplaza',
        hours: 'Open 24/7',
      },
    ],
  },
  {
    id: 'yyc-zoo',
    tenantId: 'yyc',
    keywords: ['zoo', 'calgary zoo', 'wilder', 'penguins', 'panda', 'st patrick', 'bridgeland'],
    name: 'Calgary Zoo & Wilder Institute',
    tagline: 'World-Class Conservation Island & Wildlife Experience',
    center: [51.0456, -114.0270],
    zoom: 15,
    description: 'Ranked among top zoos in North America, situated on St. George\'s Island along the Bow River with over 1,000 animals.',
    vibe: 'Family Wildlife Adventure & River Parkland',
    walkScore: 85,
    transitAccess: 'Zoo C-Train Station (Blue Line direct entrance)',
    pins: [
      {
        id: 'zoo-main-entrance',
        name: 'Calgary Zoo Main Gates',
        category: 'attraction',
        lat: 51.0465,
        lng: -114.0320,
        address: '210 St. George\'s Drive NE',
        rating: 4.8,
        highlight: 'Penguin Plunge, Canadian Wilds & Destination Africa',
        actionText: 'Buy Zoo Admission Tickets',
        actionUrl: 'https://calgaryzoo.com',
        hours: '9:00 AM - 5:00 PM Daily',
      },
      {
        id: 'st-patrick-island',
        name: 'St. Patrick\'s Island Park',
        category: 'park',
        lat: 51.0480,
        lng: -114.0410,
        address: '12 St NE (Adjacent to Zoo)',
        rating: 4.9,
        highlight: 'Trout Beach, The Rise Hill Lookout & River Pathways',
        actionText: 'Explore Island Trails',
        actionUrl: 'https://evexperience.com',
        hours: '6:00 AM - 11:00 PM',
      },
      {
        id: 'zoo-ctrain',
        name: 'Zoo C-Train Station',
        category: 'transit',
        lat: 51.0468,
        lng: -114.0335,
        address: 'Memorial Dr & Zoo Bridge',
        highlight: 'Blue Line LRT • 7 mins to Downtown Core',
        actionText: 'View Transit Times',
        actionUrl: 'https://calgarytransit.com',
        hours: 'Trains every 7-10 mins',
      },
    ],
  },
  {
    id: 'yyc-spark',
    tenantId: 'yyc',
    keywords: ['spark', 'telus spark', 'science centre', 'science center', 'dome theatre', 'spark science', 'planetarium'],
    name: 'TELUS Spark Science Centre & Brainasium',
    tagline: 'Calgary\'s Creative Science, Wonder & Discovery Hub',
    center: [51.0535, -114.0250],
    zoom: 16,
    description: 'Interactive science gallery featuring the Infinity Dome theatre, outdoor Brainasium adventure park, and hands-on maker spaces.',
    vibe: 'Interactive Discovery, Planetarium & Family Wonder',
    walkScore: 80,
    transitAccess: 'Zoo C-Train Station & Calgary Transit Route 19',
    pins: [
      {
        id: 'spark-main',
        name: 'TELUS Spark Science Centre',
        category: 'attraction',
        lat: 51.0535,
        lng: -114.0250,
        address: '220 St. George\'s Dr NE',
        rating: 4.7,
        highlight: 'Infinity Dome 8K Planetarium, Brainasium Park & Spark After Dark Adults Night',
        actionText: 'Buy Spark Admission Tickets',
        actionUrl: 'https://sparkscience.ca',
        hours: '9:00 AM - 4:00 PM Daily',
      },
      {
        id: 'spark-brainasium',
        name: 'Brainasium Outdoor Adventure Park',
        category: 'park',
        lat: 51.0542,
        lng: -114.0240,
        address: '220 St. George\'s Dr NE',
        rating: 4.8,
        highlight: '63-foot Tower Slide, 36-foot Rope Bridge & Physics Playground',
        actionText: 'Explore Brainasium',
        actionUrl: 'https://sparkscience.ca',
        hours: 'Included with Admission',
      },
      {
        id: 'bridgeland-una',
        name: 'UNA Pizza + Wine Bridgeland',
        category: 'restaurant',
        lat: 51.0548,
        lng: -114.0415,
        address: '903 1 Ave NE (3 min from Spark)',
        rating: 4.8,
        highlight: 'California-style Thin Crust Pizza & Truffle Honey (3 min west in Bridgeland)',
        actionText: 'View Bridgeland Menu',
        actionUrl: 'https://unapizzeria.com',
        hours: '11:30 AM - 10:00 PM',
        priceLevel: '$$',
      },
      {
        id: 'village-ice-cream-bridgeland',
        name: 'Village Ice Cream Bridgeland',
        category: 'restaurant',
        lat: 51.0545,
        lng: -114.0422,
        address: '69 7A St NE',
        rating: 4.9,
        highlight: 'Handcrafted Small-Batch Ice Cream (Salted Caramel, Maple Pecan)',
        actionText: 'Check Ice Cream Flavors',
        actionUrl: 'https://villageicecream.com',
        hours: 'Noon - 10:00 PM',
        priceLevel: '$',
      },
    ],
  },
  {
    id: 'yyc-tower-downtown',
    tenantId: 'yyc',
    keywords: ['calgary tower', 'tower', 'sky 360', 'centre st', 'downtown calgary'],
    name: 'Calgary Tower & Central Core',
    tagline: '360° Panoramic Rockies & City Skyline View',
    center: [51.0443, -114.0631],
    zoom: 16,
    description: 'Iconic 190.8-meter observation tower with glass-floor viewing platform and revolving restaurant.',
    vibe: 'Iconic Skyline Views & High-Altitude Dining',
    walkScore: 98,
    transitAccess: '1st Street SW C-Train Station',
    pins: [
      {
        id: 'calgary-tower-obs',
        name: 'Calgary Tower Observation Deck',
        category: 'attraction',
        lat: 51.0443,
        lng: -114.0631,
        address: '101 9 Ave SW',
        rating: 4.6,
        highlight: 'Glass-Floor Observation Deck overlooking Rockies & Olympic Plaza',
        actionText: 'Get Tower Tickets',
        actionUrl: 'https://calgarytower.com',
        hours: '10:00 AM - 9:00 PM',
      },
      {
        id: 'sky-360-restaurant',
        name: 'Sky 360 Revolving Restaurant',
        category: 'restaurant',
        lat: 51.0443,
        lng: -114.0631,
        address: '101 9 Ave SW (Top of Tower)',
        rating: 4.7,
        highlight: 'Revolving Panorama Dining with Alberta Prime Steaks',
        actionText: 'Reserve Table on OpenTable',
        actionUrl: 'https://opentable.com/sky-360',
        hours: '11:30 AM - 10:00 PM',
        priceLevel: '$$$$',
      },
    ],
  },
  {
    id: 'yyc-17th-ave',
    tenantId: 'yyc',
    keywords: ['17th ave', '17th avenue', 'red mile', 'beltline', 'una pizza', 'ship and anchor'],
    name: '17th Avenue SW Entertainment District',
    tagline: 'Calgary\'s Vibrant Dining & Nightlife Epicenter',
    center: [51.0379, -114.0780],
    zoom: 16,
    description: 'Over 400 retail shops, patio bars, boutique cafes, and chef-driven dining rooms along the legendary Red Mile.',
    vibe: 'Buzzing Patios, Craft Beer & Artisanal Cocktails',
    walkScore: 96,
    transitAccess: 'Bus Routes 2, 6, 7 & 10 mins walk from Victoria Park C-Train',
    pins: [
      {
        id: 'model-milk',
        name: 'Model Milk',
        category: 'restaurant',
        lat: 51.0378,
        lng: -114.0685,
        address: '308 17 Ave SW',
        rating: 4.8,
        highlight: 'Inventive Comfort Food in Converted 1930s Dairy Building',
        actionText: 'Reserve on OpenTable',
        actionUrl: 'https://opentable.com/model-milk',
        hours: '5:00 PM - Late',
        priceLevel: '$$$',
      },
      {
        id: 'una-pizza',
        name: 'UNA Pizza + Wine',
        category: 'restaurant',
        lat: 51.0379,
        lng: -114.0748,
        address: '618 17 Ave SW',
        rating: 4.7,
        highlight: 'California-style Thin Crust Pizza & Spanish Charcuterie',
        actionText: 'Check Waitlist Online',
        actionUrl: 'https://unapizzeria.com',
        hours: '11:30 AM - Midnight',
        priceLevel: '$$',
      },
      {
        id: 'ship-and-anchor',
        name: 'Ship & Anchor Pub',
        category: 'restaurant',
        lat: 51.0380,
        lng: -114.0725,
        address: '534 17 Ave SW',
        rating: 4.7,
        highlight: 'Iconic Legendary Live Music & Football Pub with Sunny Patio',
        actionText: 'View Live Gig Lineup',
        actionUrl: 'https://shipandanchor.com',
        hours: '11:00 AM - 2:00 AM',
        priceLevel: '$$',
      },
      {
        id: 'lulu-bar',
        name: 'Lulu Bar',
        category: 'restaurant',
        lat: 51.0377,
        lng: -114.0710,
        address: '510 17 Ave SW',
        rating: 4.8,
        highlight: 'Pacific Coast & Polynesian Bites, Yakitori Skewers & Tiki Drinks',
        actionText: 'Book on OpenTable',
        actionUrl: 'https://opentable.com/lulu-bar',
        hours: '4:00 PM - 11:00 PM',
        priceLevel: '$$$',
      },
    ],
  },
  {
    id: 'yyc-princes-island',
    tenantId: 'yyc',
    keywords: ['princes island', 'prince\'s island', 'river cafe', 'peace bridge', 'bow river', 'eau claire'],
    name: 'Prince\'s Island Park & Peace Bridge',
    tagline: 'Tranquil River Oasis & Fine Waterfront Dining',
    center: [51.0545, -114.0710],
    zoom: 16,
    description: 'Lush 20-hectare park in the Bow River hosting outdoor festivals, home to River Café, linked by the iconic Santiago Calatrava Peace Bridge.',
    vibe: 'Scenic River Walks, Architecture & Sustainable Fine Dining',
    walkScore: 94,
    transitAccess: '5 mins walk from 7th Street C-Train Station',
    pins: [
      {
        id: 'river-cafe',
        name: 'River Café',
        category: 'restaurant',
        lat: 51.0542,
        lng: -114.0708,
        address: '25 Prince\'s Island Park',
        rating: 4.9,
        highlight: 'Michelin-level Hyper-local Foraged Canadian Cuisine with Stone Fireplace',
        actionText: 'Book Table on OpenTable',
        actionUrl: 'https://opentable.com/river-cafe-calgary',
        hours: '11:00 AM - 9:30 PM',
        priceLevel: '$$$$',
      },
      {
        id: 'peace-bridge',
        name: 'Peace Bridge (Santiago Calatrava)',
        category: 'attraction',
        lat: 51.0538,
        lng: -114.0792,
        address: 'Bow River at 8 St SW',
        highlight: 'Architectural Masterpiece connecting Downtown to Sunnyside',
        actionText: 'View Photo Guide',
        actionUrl: 'https://calgary.ca/peacebridge',
        hours: 'Open 24/7',
      },
    ],
  },

  // ================= TORONTO (YYZ) =================
  {
    id: 'yyz-king-west',
    tenantId: 'yyz',
    keywords: ['king west', 'king street west', 'theatre district', 'alo', 'tiff', 'princess of wales'],
    name: 'King Street West & Theatre District',
    tagline: 'Toronto\'s High-Energy Culinary & Broadway Corridor',
    center: [43.6475, -79.3905],
    zoom: 16,
    description: 'The heartbeat of downtown Toronto culture, featuring Michelin-starred dining, Broadway musicals, and chic rooftop lounges.',
    vibe: 'Michelin Gastronomy, Broadway Theatre & Vibrant Lounges',
    walkScore: 100,
    transitAccess: 'St. Andrew Subway Station & 504 King Streetcar',
    pins: [
      {
        id: 'alo-toronto',
        name: 'Alo Restaurant',
        category: 'restaurant',
        lat: 43.6483,
        lng: -79.3965,
        address: '163 Spadina Ave (at King W)',
        rating: 4.9,
        highlight: 'Michelin Starred French Tasting Menu on Top Floor',
        actionText: 'Book on OpenTable',
        actionUrl: 'https://opentable.com/alo-restaurant',
        hours: '5:00 PM - 10:30 PM',
        priceLevel: '$$$$',
      },
      {
        id: 'princess-of-wales',
        name: 'Princess of Wales Theatre',
        category: 'theatre',
        lat: 43.6471,
        lng: -79.3892,
        address: '300 King St W',
        highlight: 'Home to Disney\'s The Lion King & Major World Premieres',
        actionText: 'Get Tickets on Mirvish',
        actionUrl: 'https://mirvish.com',
        hours: 'Showtimes 1:30 PM & 7:30 PM',
      },
      {
        id: 'tiff-lightbox',
        name: 'TIFF Bell Lightbox',
        category: 'theatre',
        lat: 43.6465,
        lng: -79.3902,
        address: '350 King St W',
        highlight: 'Global Cinema Headquarters & Toronto Int\'l Film Festival Hub',
        actionText: 'View Screenings',
        actionUrl: 'https://tiff.net',
        hours: '11:00 AM - 10:00 PM',
      },
    ],
  },
  {
    id: 'yyz-distillery',
    tenantId: 'yyz',
    keywords: ['distillery', 'distillery district', 'el catrin', 'cluny', 'mill street', 'gooderham'],
    name: 'Distillery Historic District',
    tagline: 'North America\'s Premier Victorian Industrial Village',
    center: [43.6503, -79.3592],
    zoom: 16,
    description: 'Cobblestone streets with 47 19th-century Victorian brick buildings, artisanal bakeries, distilleries, and open-air sculpture galleries.',
    vibe: 'Historic Cobblestone Charm, Craft Spirits & Tapas Patios',
    walkScore: 95,
    transitAccess: '504 King Streetcar & 121 Esplanade Bus',
    pins: [
      {
        id: 'el-catrin',
        name: 'El Catrin Destileria',
        category: 'restaurant',
        lat: 43.6506,
        lng: -79.3585,
        address: '18 Tank House Lane',
        rating: 4.8,
        highlight: 'Modern Mexican Tapas & Canada\'s Largest Tequila Collection on Mega-Patio',
        actionText: 'Book Table on OpenTable',
        actionUrl: 'https://opentable.com/el-catrin',
        hours: '12:00 PM - 11:00 PM',
        priceLevel: '$$$',
      },
      {
        id: 'cluny-bistro',
        name: 'Cluny Bistro & Boulangerie',
        category: 'restaurant',
        lat: 43.6501,
        lng: -79.3598,
        address: '35 Tank House Lane',
        rating: 4.7,
        highlight: 'Neo-Parisian Brasserie with Fresh Croissants & Duck Confit',
        actionText: 'Reserve Table on OpenTable',
        actionUrl: 'https://opentable.com/cluny-bistro',
        hours: '11:30 AM - 10:00 PM',
        priceLevel: '$$$',
      },
      {
        id: 'spirit-of-york',
        name: 'Spirit of York Distillery Co.',
        category: 'attraction',
        lat: 43.6509,
        lng: -79.3590,
        address: '12 Trinity St',
        highlight: 'Artisanal Gin & Vodka Distilled in Heritage Bitters Glasshouse',
        actionText: 'Book Tasting Flight',
        actionUrl: 'https://spiritofyork.com',
        hours: '12:00 PM - 9:00 PM',
      },
    ],
  },
  {
    id: 'yyz-zoo',
    tenantId: 'yyz',
    keywords: ['zoo', 'toronto zoo', 'wildlife', 'rouge', 'scarborough zoo', 'animals', 'polar bear'],
    name: 'Toronto Zoo & Rouge National Park',
    tagline: 'Canada\'s Premier 710-Acre Living Kingdom',
    center: [43.8177, -79.1859],
    zoom: 15,
    description: 'Encounter over 5,000 animals across 7 geographic pavilions in the scenic Rouge River Valley.',
    vibe: 'World Wildlife Immersion & Conservation',
    walkScore: 75,
    transitAccess: 'TTC 86A Scarborough Bus from Kennedy Subway Station',
    pins: [
      {
        id: 'toronto-zoo-main',
        name: 'Toronto Zoo Main Pavilions',
        category: 'attraction',
        lat: 43.8180,
        lng: -79.1865,
        address: '2000 Meadowvale Rd, Scarborough',
        rating: 4.8,
        highlight: 'Tundra Trek Polar Bears, Gorilla Rainforest & Splash Island',
        actionText: 'Buy Zoo Passes Online',
        actionUrl: 'https://torontozoo.com',
        hours: '9:30 AM - 4:30 PM Daily',
      },
      {
        id: 'rouge-national-park',
        name: 'Rouge National Urban Park',
        category: 'park',
        lat: 43.8150,
        lng: -79.1790,
        address: '1749 Meadowvale Rd',
        rating: 4.9,
        highlight: 'North America\'s Largest Urban Protected Wilderness & River Trails',
        actionText: 'Explore Trail Map',
        actionUrl: 'https://parks.canada.ca/pn-np/on/rouge',
        hours: 'Open Sunrise to Sunset',
      },
      {
        id: 'black-dog-pub',
        name: 'The Black Dog Pub',
        category: 'restaurant',
        lat: 43.8050,
        lng: -79.1620,
        address: '87 Island Rd, Scarborough',
        rating: 4.6,
        highlight: 'Classic English Pub Fare, Fish & Chips & Craft Ales (5 min from Zoo)',
        actionText: 'View Pub Menu',
        actionUrl: 'https://blackdogpub.ca',
        hours: '11:30 AM - 11:00 PM',
        priceLevel: '$$',
      },
      {
        id: 'pickering-casino-hotel',
        name: 'Pickering Casino Resort & Hotel',
        category: 'hotel',
        lat: 43.8350,
        lng: -79.0650,
        address: '888 Durham Live Ave',
        rating: 4.7,
        highlight: 'Luxury Modern Resort with 275 Suites (8 min east of Toronto Zoo)',
        actionText: 'Book Room on Booking.com',
        actionUrl: 'https://booking.com',
        priceLevel: '$$$',
      },
      {
        id: 'ttc-zoo-express',
        name: 'TTC Zoo Express Loop',
        category: 'transit',
        lat: 43.8190,
        lng: -79.1850,
        address: 'Toronto Zoo Bus Loop',
        highlight: 'Direct Transit Connection to Kennedy Subway & Rouge Hill GO',
        actionText: 'View TTC Schedule',
        actionUrl: 'https://ttc.ca',
        hours: 'Every 15-20 mins',
      },
    ],
  },

  // ================= VANCOUVER (YVR) =================
  {
    id: 'yvr-gastown',
    tenantId: 'yvr',
    keywords: ['gastown', 'steam clock', 'l\'abattoir', 'water st', 'water street'],
    name: 'Gastown Historic Quarter',
    tagline: 'Vancouver\'s Oldest Neighborhood & Culinary Hub',
    center: [49.2838, -123.1090],
    zoom: 16,
    description: 'Historic brick facades, vintage lampposts, Victorian Steam Clock, and acclaimed cocktail bars.',
    vibe: 'Brick Heritage, Speakeasy Cocktails & West Coast Cuisine',
    walkScore: 99,
    transitAccess: 'Waterfront SkyTrain Station (Expo, Millennium & Canada Lines)',
    pins: [
      {
        id: 'labattoir',
        name: 'L\'Abattoir',
        category: 'restaurant',
        lat: 49.2838,
        lng: -123.1090,
        address: '217 Carrall St',
        rating: 4.9,
        highlight: 'Refined French-influenced West Coast Fare in Refurbished 19th Century Butchery',
        actionText: 'Book Table on OpenTable',
        actionUrl: 'https://opentable.com/labattoir',
        hours: '5:00 PM - 10:00 PM',
        priceLevel: '$$$$',
      },
      {
        id: 'steam-clock',
        name: 'Gastown Steam Clock',
        category: 'attraction',
        lat: 49.2845,
        lng: -123.1089,
        address: '305 Water St',
        highlight: 'World-Famous Working 1977 Antique Steam Chime Clock',
        actionText: 'View Historic Guide',
        actionUrl: 'https://gastown.org',
        hours: 'Chimes every 15 minutes',
      },
    ],
  },
  {
    id: 'yvr-stanley-park',
    tenantId: 'yvr',
    keywords: ['stanley park', 'aquarium', 'seawall', 'prospect point', 'vancouver aquarium'],
    name: 'Stanley Park & Vancouver Aquarium',
    tagline: '400-Hectare Rainforest Oasis & Pacific Seawall',
    center: [49.3017, -123.1310],
    zoom: 15,
    description: 'World-renowned urban park surrounded by English Bay waters, cedar rainforest, and the famous 9km Seawall.',
    vibe: 'Pacific Coast Rainforest, Ocean Cycling & Marine Life',
    walkScore: 90,
    transitAccess: 'TransLink Bus 19 direct to Stanley Park Loop',
    pins: [
      {
        id: 'van-aquarium',
        name: 'Vancouver Aquarium (Ocean Wise)',
        category: 'attraction',
        lat: 49.3006,
        lng: -123.1312,
        address: '845 Avison Way (Stanley Park)',
        rating: 4.8,
        highlight: 'Rescued Sea Otters, Amazon Rainforest & Steller Sea Lions',
        actionText: 'Book Aquarium Tickets',
        actionUrl: 'https://vanaqua.org',
        hours: '10:00 AM - 5:00 PM Daily',
      },
      {
        id: 'prospect-point',
        name: 'Prospect Point Lookout',
        category: 'park',
        lat: 49.3142,
        lng: -123.1415,
        address: '5601 Stanley Park Dr',
        highlight: 'Spectacular Vistas of Lions Gate Bridge & Burrard Inlet',
        actionText: 'View Lookout Guide',
        actionUrl: 'https://vancouver.ca/parks-recreation-culture/stanley-park.aspx',
        hours: 'Open Dawn to Dusk',
      },
    ],
  },
];

export function findMatchingGeoSpotlight(
  query: string,
  tenantId: string
): GeoSpotlightDistrict | null {
  const normalized = query.toLowerCase();

  // First search strictly within the current tenant's spotlights
  const citySpotlights = CANADIAN_GEO_SPOTLIGHTS.filter(
    (s) => s.tenantId.toLowerCase() === tenantId.toLowerCase()
  );

  for (const district of citySpotlights) {
    for (const keyword of district.keywords) {
      if (normalized.includes(keyword)) {
        return district;
      }
    }
  }

  // Fallback: Check if any generic landmark matches
  for (const district of citySpotlights) {
    for (const pin of district.pins) {
      if (normalized.includes(pin.name.toLowerCase())) {
        return district;
      }
    }
  }

  return null;
}
