export interface MapPinPoint {
  id: string;
  name: string;
  category: 'restaurant' | 'attraction' | 'theatre' | 'transit' | 'hotel' | 'park';
  lat: number;
  lng: number;
  address: string;
  rating?: number;
  highlight: string;
  actionText: string;
  actionUrl: string;
  hours?: string;
  priceLevel?: string;
}

export interface GeoSpotlightDistrict {
  id: string;
  tenantId: string;
  keywords: string[];
  name: string;
  tagline: string;
  center: [number, number]; // [lat, lng]
  zoom: number;
  description: string;
  vibe: string;
  walkScore: number;
  transitAccess: string;
  pins: MapPinPoint[];
}

export const CANADIAN_GEO_SPOTLIGHTS: GeoSpotlightDistrict[] = [
  // ================= CALGARY (YYC) =================
  {
    id: 'yyc-stephen-ave',
    tenantId: 'yyc',
    keywords: ['stephen ave', 'stephen avenue', '8th ave', 'downtown calgary', 'stephen'],
    name: 'Stephen Avenue Walk',
    tagline: 'Calgary\'s Historic Heritage Pedestrian Mall',
    center: [51.0458, -114.0680],
    zoom: 16,
    description: 'Bustling pedestrian promenade lined with sandstone heritage architecture, award-winning steakhouses, lively patios, and street buskers.',
    vibe: 'Sophisticated Dining, Heritage Cocktails & Live Music',
    walkScore: 98,
    transitAccess: '1st St SW & Centre St C-Train Stations (Free Fare Zone)',
    pins: [
      {
        id: 'major-tom',
        name: 'Major Tom Bar',
        category: 'restaurant',
        lat: 51.0455,
        lng: -114.0689,
        address: '40th Floor, 700 2 St SW',
        rating: 4.9,
        highlight: '40-Floor Skyview • Dry-Aged Alberta Prime Rib • Vintage Cocktails',
        actionText: 'Book Table on SevenRooms',
        actionUrl: 'https://sevenrooms.com/reservations/majortombar',
        hours: '5:00 PM - 11:00 PM Daily',
        priceLevel: '$$$$',
      },
      {
        id: 'teatro',
        name: 'Teatro Ristorante',
        category: 'restaurant',
        lat: 51.0459,
        lng: -114.0601,
        address: '200 8 Ave SE (Olympic Plaza)',
        rating: 4.8,
        highlight: 'Classic Mediterranean Fine Dining in 1911 Dominion Bank',
        actionText: 'Reserve on OpenTable',
        actionUrl: 'https://opentable.com/teatro',
        hours: '5:00 PM - 10:00 PM',
        priceLevel: '$$$$',
      },
      {
        id: 'charcut',
        name: 'Charcut Roast House',
        category: 'restaurant',
        lat: 51.0461,
        lng: -114.0628,
        address: '899 Centre St S',
        rating: 4.7,
        highlight: 'Butcher-driven Rotisserie & House-cured Charcuterie',
        actionText: 'Book Table on OpenTable',
        actionUrl: 'https://opentable.com/charcut',
        hours: '11:30 AM - 10:00 PM',
        priceLevel: '$$$',
      },
      {
        id: 'glenbow',
        name: 'Glenbow Museum & Art Gallery',
        category: 'attraction',
        lat: 51.0449,
        lng: -114.0608,
        address: '130 9 Ave SE',
        highlight: 'Western Canada\'s Largest Arts & Culture Collection',
        actionText: 'Get Museum Passes',
        actionUrl: 'https://glenbow.org',
        hours: '10:00 AM - 5:00 PM',
      },
      {
        id: 'olympic-plaza',
        name: 'Olympic Plaza',
        category: 'park',
        lat: 51.0460,
        lng: -114.0592,
        address: '228 8 Ave SE',
        highlight: '1988 Olympic Medal Site • Winter Skating & Summer Stage',
        actionText: 'View Plaza Events',
        actionUrl: 'https://calgary.ca/olympicplaza',
        hours: 'Open 24/7',
      },
    ],
  },
  {
    id: 'yyc-zoo',
    tenantId: 'yyc',
    keywords: ['zoo', 'calgary zoo', 'wilder', 'penguins', 'panda', 'st patrick', 'bridgeland'],
    name: 'Calgary Zoo & Wilder Institute',
    tagline: 'World-Class Conservation Island & Wildlife Experience',
    center: [51.0456, -114.0270],
    zoom: 15,
    description: 'Ranked among top zoos in North America, situated on St. George\'s Island along the Bow River with over 1,000 animals.',
    vibe: 'Family Wildlife Adventure & River Parkland',
    walkScore: 85,
    transitAccess: 'Zoo C-Train Station (Blue Line direct entrance)',
    pins: [
      {
        id: 'zoo-main-entrance',
        name: 'Calgary Zoo Main Gates',
        category: 'attraction',
        lat: 51.0465,
        lng: -114.0320,
        address: '210 St. George\'s Drive NE',
        rating: 4.8,
        highlight: 'Penguin Plunge, Canadian Wilds & Destination Africa',
        actionText: 'Buy Zoo Admission Tickets',
        actionUrl: 'https://calgaryzoo.com',
        hours: '9:00 AM - 5:00 PM Daily',
      },
      {
        id: 'st-patrick-island',
        name: 'St. Patrick\'s Island Park',
        category: 'park',
        lat: 51.0480,
        lng: -114.0410,
        address: '12 St NE (Adjacent to Zoo)',
        rating: 4.9,
        highlight: 'Trout Beach, The Rise Hill Lookout & River Pathways',
        actionText: 'Explore Island Trails',
        actionUrl: 'https://evexperience.com',
        hours: '6:00 AM - 11:00 PM',
      },
      {
        id: 'zoo-ctrain',
        name: 'Zoo C-Train Station',
        category: 'transit',
        lat: 51.0468,
        lng: -114.0335,
        address: 'Memorial Dr & Zoo Bridge',
        highlight: 'Blue Line LRT • 7 mins to Downtown Core',
        actionText: 'View Transit Times',
        actionUrl: 'https://calgarytransit.com',
        hours: 'Trains every 7-10 mins',
      },
    ],
  },
  {
    id: 'yyc-spark',
    tenantId: 'yyc',
    keywords: ['spark', 'telus spark', 'science centre', 'science center', 'dome theatre', 'spark science', 'planetarium'],
    name: 'TELUS Spark Science Centre & Brainasium',
    tagline: 'Calgary\'s Creative Science, Wonder & Discovery Hub',
    center: [51.0535, -114.0250],
    zoom: 16,
    description: 'Interactive science gallery featuring the Infinity Dome theatre, outdoor Brainasium adventure park, and hands-on maker spaces.',
    vibe: 'Interactive Discovery, Planetarium & Family Wonder',
    walkScore: 80,
    transitAccess: 'Zoo C-Train Station & Calgary Transit Route 19',
    pins: [
      {
        id: 'spark-main',
        name: 'TELUS Spark Science Centre',
        category: 'attraction',
        lat: 51.0535,
        lng: -114.0250,
        address: '220 St. George\'s Dr NE',
        rating: 4.7,
        highlight: 'Infinity Dome 8K Planetarium, Brainasium Park & Spark After Dark Adults Night',
        actionText: 'Buy Spark Admission Tickets',
        actionUrl: 'https://sparkscience.ca',
        hours: '9:00 AM - 4:00 PM Daily',
      },
      {
        id: 'spark-brainasium',
        name: 'Brainasium Outdoor Adventure Park',
        category: 'park',
        lat: 51.0542,
        lng: -114.0240,
        address: '220 St. George\'s Dr NE',
        rating: 4.8,
        highlight: '63-foot Tower Slide, 36-foot Rope Bridge & Physics Playground',
        actionText: 'Explore Brainasium',
        actionUrl: 'https://sparkscience.ca',
        hours: 'Included with Admission',
      },
      {
        id: 'bridgeland-una',
        name: 'UNA Pizza + Wine Bridgeland',
        category: 'restaurant',
        lat: 51.0548,
        lng: -114.0415,
        address: '903 1 Ave NE (3 min from Spark)',
        rating: 4.8,
        highlight: 'California-style Thin Crust Pizza & Truffle Honey (3 min west in Bridgeland)',
        actionText: 'View Bridgeland Menu',
        actionUrl: 'https://unapizzeria.com',
        hours: '11:30 AM - 10:00 PM',
        priceLevel: '$$',
      },
      {
        id: 'village-ice-cream-bridgeland',
        name: 'Village Ice Cream Bridgeland',
        category: 'restaurant',
        lat: 51.0545,
        lng: -114.0422,
        address: '69 7A St NE',
        rating: 4.9,
        highlight: 'Handcrafted Small-Batch Ice Cream (Salted Caramel, Maple Pecan)',
        actionText: 'Check Ice Cream Flavors',
        actionUrl: 'https://villageicecream.com',
        hours: 'Noon - 10:00 PM',
        priceLevel: '$',
      },
    ],
  },
  {
    id: 'yyc-tower-downtown',
    tenantId: 'yyc',
    keywords: ['calgary tower', 'tower', 'sky 360', 'centre st', 'downtown calgary'],
    name: 'Calgary Tower & Central Core',
    tagline: '360° Panoramic Rockies & City Skyline View',
    center: [51.0443, -114.0631],
    zoom: 16,
    description: 'Iconic 190.8-meter observation tower with glass-floor viewing platform and revolving restaurant.',
    vibe: 'Iconic Skyline Views & High-Altitude Dining',
    walkScore: 98,
    transitAccess: '1st Street SW C-Train Station',
    pins: [
      {
        id: 'calgary-tower-obs',
        name: 'Calgary Tower Observation Deck',
        category: 'attraction',
        lat: 51.0443,
        lng: -114.0631,
        address: '101 9 Ave SW',
        rating: 4.6,
        highlight: 'Glass-Floor Observation Deck overlooking Rockies & Olympic Plaza',
        actionText: 'Get Tower Tickets',
        actionUrl: 'https://calgarytower.com',
        hours: '10:00 AM - 9:00 PM',
      },
      {
        id: 'sky-360-restaurant',
        name: 'Sky 360 Revolving Restaurant',
        category: 'restaurant',
        lat: 51.0443,
        lng: -114.0631,
        address: '101 9 Ave SW (Top of Tower)',
        rating: 4.7,
        highlight: 'Revolving Panorama Dining with Alberta Prime Steaks',
        actionText: 'Reserve Table on OpenTable',
        actionUrl: 'https://opentable.com/sky-360',
        hours: '11:30 AM - 10:00 PM',
        priceLevel: '$$$$',
      },
    ],
  },
  {
    id: 'yyc-17th-ave',
    tenantId: 'yyc',
    keywords: ['17th ave', '17th avenue', 'red mile', 'beltline', 'una pizza', 'ship and anchor'],
    name: '17th Avenue SW Entertainment District',
    tagline: 'Calgary\'s Vibrant Dining & Nightlife Epicenter',
    center: [51.0379, -114.0780],
    zoom: 16,
    description: 'Over 400 retail shops, patio bars, boutique cafes, and chef-driven dining rooms along the legendary Red Mile.',
    vibe: 'Buzzing Patios, Craft Beer & Artisanal Cocktails',
    walkScore: 96,
    transitAccess: 'Bus Routes 2, 6, 7 & 10 mins walk from Victoria Park C-Train',
    pins: [
      {
        id: 'model-milk',
        name: 'Model Milk',
        category: 'restaurant',
        lat: 51.0378,
        lng: -114.0685,
        address: '308 17 Ave SW',
        rating: 4.8,
        highlight: 'Inventive Comfort Food in Converted 1930s Dairy Building',
        actionText: 'Reserve on OpenTable',
        actionUrl: 'https://opentable.com/model-milk',
        hours: '5:00 PM - Late',
        priceLevel: '$$$',
      },
      {
        id: 'una-pizza',
        name: 'UNA Pizza + Wine',
        category: 'restaurant',
        lat: 51.0379,
        lng: -114.0748,
        address: '618 17 Ave SW',
        rating: 4.7,
        highlight: 'California-style Thin Crust Pizza & Spanish Charcuterie',
        actionText: 'Check Waitlist Online',
        actionUrl: 'https://unapizzeria.com',
        hours: '11:30 AM - Midnight',
        priceLevel: '$$',
      },
      {
        id: 'ship-and-anchor',
        name: 'Ship & Anchor Pub',
        category: 'restaurant',
        lat: 51.0380,
        lng: -114.0725,
        address: '534 17 Ave SW',
        rating: 4.7,
        highlight: 'Iconic Legendary Live Music & Football Pub with Sunny Patio',
        actionText: 'View Live Gig Lineup',
        actionUrl: 'https://shipandanchor.com',
        hours: '11:00 AM - 2:00 AM',
        priceLevel: '$$',
      },
      {
        id: 'lulu-bar',
        name: 'Lulu Bar',
        category: 'restaurant',
        lat: 51.0377,
        lng: -114.0710,
        address: '510 17 Ave SW',
        rating: 4.8,
        highlight: 'Pacific Coast & Polynesian Bites, Yakitori Skewers & Tiki Drinks',
        actionText: 'Book on OpenTable',
        actionUrl: 'https://opentable.com/lulu-bar',
        hours: '4:00 PM - 11:00 PM',
        priceLevel: '$$$',
      },
    ],
  },
  {
    id: 'yyc-princes-island',
    tenantId: 'yyc',
    keywords: ['princes island', 'prince\'s island', 'river cafe', 'peace bridge', 'bow river', 'eau claire'],
    name: 'Prince\'s Island Park & Peace Bridge',
    tagline: 'Tranquil River Oasis & Fine Waterfront Dining',
    center: [51.0545, -114.0710],
    zoom: 16,
    description: 'Lush 20-hectare park in the Bow River hosting outdoor festivals, home to River Café, linked by the iconic Santiago Calatrava Peace Bridge.',
    vibe: 'Scenic River Walks, Architecture & Sustainable Fine Dining',
    walkScore: 94,
    transitAccess: '5 mins walk from 7th Street C-Train Station',
    pins: [
      {
        id: 'river-cafe',
        name: 'River Café',
        category: 'restaurant',
        lat: 51.0542,
        lng: -114.0708,
        address: '25 Prince\'s Island Park',
        rating: 4.9,
        highlight: 'Michelin-level Hyper-local Foraged Canadian Cuisine with Stone Fireplace',
        actionText: 'Book Table on OpenTable',
        actionUrl: 'https://opentable.com/river-cafe-calgary',
        hours: '11:00 AM - 9:30 PM',
        priceLevel: '$$$$',
      },
      {
        id: 'peace-bridge',
        name: 'Peace Bridge (Santiago Calatrava)',
        category: 'attraction',
        lat: 51.0538,
        lng: -114.0792,
        address: 'Bow River at 8 St SW',
        highlight: 'Architectural Masterpiece connecting Downtown to Sunnyside',
        actionText: 'View Photo Guide',
        actionUrl: 'https://calgary.ca/peacebridge',
        hours: 'Open 24/7',
      },
    ],
  },

  // ================= TORONTO (YYZ) =================
  {
    id: 'yyz-king-west',
    tenantId: 'yyz',
    keywords: ['king west', 'king street west', 'theatre district', 'alo', 'tiff', 'princess of wales'],
    name: 'King Street West & Theatre District',
    tagline: 'Toronto\'s High-Energy Culinary & Broadway Corridor',
    center: [43.6475, -79.3905],
    zoom: 16,
    description: 'The heartbeat of downtown Toronto culture, featuring Michelin-starred dining, Broadway musicals, and chic rooftop lounges.',
    vibe: 'Michelin Gastronomy, Broadway Theatre & Vibrant Lounges',
    walkScore: 100,
    transitAccess: 'St. Andrew Subway Station & 504 King Streetcar',
    pins: [
      {
        id: 'alo-toronto',
        name: 'Alo Restaurant',
        category: 'restaurant',
        lat: 43.6483,
        lng: -79.3965,
        address: '163 Spadina Ave (at King W)',
        rating: 4.9,
        highlight: 'Michelin Starred French Tasting Menu on Top Floor',
        actionText: 'Book on OpenTable',
        actionUrl: 'https://opentable.com/alo-restaurant',
        hours: '5:00 PM - 10:30 PM',
        priceLevel: '$$$$',
      },
      {
        id: 'princess-of-wales',
        name: 'Princess of Wales Theatre',
        category: 'theatre',
        lat: 43.6471,
        lng: -79.3892,
        address: '300 King St W',
        highlight: 'Home to Disney\'s The Lion King & Major World Premieres',
        actionText: 'Get Tickets on Mirvish',
        actionUrl: 'https://mirvish.com',
        hours: 'Showtimes 1:30 PM & 7:30 PM',
      },
      {
        id: 'tiff-lightbox',
        name: 'TIFF Bell Lightbox',
        category: 'theatre',
        lat: 43.6465,
        lng: -79.3902,
        address: '350 King St W',
        highlight: 'Global Cinema Headquarters & Toronto Int\'l Film Festival Hub',
        actionText: 'View Screenings',
        actionUrl: 'https://tiff.net',
        hours: '11:00 AM - 10:00 PM',
      },
    ],
  },
  {
    id: 'yyz-distillery',
    tenantId: 'yyz',
    keywords: ['distillery', 'distillery district', 'el catrin', 'cluny', 'mill street', 'gooderham'],
    name: 'Distillery Historic District',
    tagline: 'North America\'s Premier Victorian Industrial Village',
    center: [43.6503, -79.3592],
    zoom: 16,
    description: 'Cobblestone streets with 47 19th-century Victorian brick buildings, artisanal bakeries, distilleries, and open-air sculpture galleries.',
    vibe: 'Historic Cobblestone Charm, Craft Spirits & Tapas Patios',
    walkScore: 95,
    transitAccess: '504 King Streetcar & 121 Esplanade Bus',
    pins: [
      {
        id: 'el-catrin',
        name: 'El Catrin Destileria',
        category: 'restaurant',
        lat: 43.6506,
        lng: -79.3585,
        address: '18 Tank House Lane',
        rating: 4.8,
        highlight: 'Modern Mexican Tapas & Canada\'s Largest Tequila Collection on Mega-Patio',
        actionText: 'Book Table on OpenTable',
        actionUrl: 'https://opentable.com/el-catrin',
        hours: '12:00 PM - 11:00 PM',
        priceLevel: '$$$',
      },
      {
        id: 'cluny-bistro',
        name: 'Cluny Bistro & Boulangerie',
        category: 'restaurant',
        lat: 43.6501,
        lng: -79.3598,
        address: '35 Tank House Lane',
        rating: 4.7,
        highlight: 'Neo-Parisian Brasserie with Fresh Croissants & Duck Confit',
        actionText: 'Reserve Table on OpenTable',
        actionUrl: 'https://opentable.com/cluny-bistro',
        hours: '11:30 AM - 10:00 PM',
        priceLevel: '$$$',
      },
      {
        id: 'spirit-of-york',
        name: 'Spirit of York Distillery Co.',
        category: 'attraction',
        lat: 43.6509,
        lng: -79.3590,
        address: '12 Trinity St',
        highlight: 'Artisanal Gin & Vodka Distilled in Heritage Bitters Glasshouse',
        actionText: 'Book Tasting Flight',
        actionUrl: 'https://spiritofyork.com',
        hours: '12:00 PM - 9:00 PM',
      },
    ],
  },
  {
    id: 'yyz-zoo',
    tenantId: 'yyz',
    keywords: ['zoo', 'toronto zoo', 'wildlife', 'rouge', 'scarborough zoo', 'animals', 'polar bear'],
    name: 'Toronto Zoo & Rouge National Park',
    tagline: 'Canada\'s Premier 710-Acre Living Kingdom',
    center: [43.8177, -79.1859],
    zoom: 15,
    description: 'Encounter over 5,000 animals across 7 geographic pavilions in the scenic Rouge River Valley.',
    vibe: 'World Wildlife Immersion & Conservation',
    walkScore: 75,
    transitAccess: 'TTC 86A Scarborough Bus from Kennedy Subway Station',
    pins: [
      {
        id: 'toronto-zoo-main',
        name: 'Toronto Zoo Main Pavilions',
        category: 'attraction',
        lat: 43.8180,
        lng: -79.1865,
        address: '2000 Meadowvale Rd, Scarborough',
        rating: 4.8,
        highlight: 'Tundra Trek Polar Bears, Gorilla Rainforest & Splash Island',
        actionText: 'Buy Zoo Passes Online',
        actionUrl: 'https://torontozoo.com',
        hours: '9:30 AM - 4:30 PM Daily',
      },
      {
        id: 'rouge-national-park',
        name: 'Rouge National Urban Park',
        category: 'park',
        lat: 43.8150,
        lng: -79.1790,
        address: '1749 Meadowvale Rd',
        rating: 4.9,
        highlight: 'North America\'s Largest Urban Protected Wilderness & River Trails',
        actionText: 'Explore Trail Map',
        actionUrl: 'https://parks.canada.ca/pn-np/on/rouge',
        hours: 'Open Sunrise to Sunset',
      },
      {
        id: 'black-dog-pub',
        name: 'The Black Dog Pub',
        category: 'restaurant',
        lat: 43.8050,
        lng: -79.1620,
        address: '87 Island Rd, Scarborough',
        rating: 4.6,
        highlight: 'Classic English Pub Fare, Fish & Chips & Craft Ales (5 min from Zoo)',
        actionText: 'View Pub Menu',
        actionUrl: 'https://blackdogpub.ca',
        hours: '11:30 AM - 11:00 PM',
        priceLevel: '$$',
      },
      {
        id: 'pickering-casino-hotel',
        name: 'Pickering Casino Resort & Hotel',
        category: 'hotel',
        lat: 43.8350,
        lng: -79.0650,
        address: '888 Durham Live Ave',
        rating: 4.7,
        highlight: 'Luxury Modern Resort with 275 Suites (8 min east of Toronto Zoo)',
        actionText: 'Book Room on Booking.com',
        actionUrl: 'https://booking.com',
        priceLevel: '$$$',
      },
      {
        id: 'ttc-zoo-express',
        name: 'TTC Zoo Express Loop',
        category: 'transit',
        lat: 43.8190,
        lng: -79.1850,
        address: 'Toronto Zoo Bus Loop',
        highlight: 'Direct Transit Connection to Kennedy Subway & Rouge Hill GO',
        actionText: 'View TTC Schedule',
        actionUrl: 'https://ttc.ca',
        hours: 'Every 15-20 mins',
      },
    ],
  },

  // ================= VANCOUVER (YVR) =================
  {
    id: 'yvr-gastown',
    tenantId: 'yvr',
    keywords: ['gastown', 'steam clock', 'l\'abattoir', 'water st', 'water street'],
    name: 'Gastown Historic Quarter',
    tagline: 'Vancouver\'s Oldest Neighborhood & Culinary Hub',
    center: [49.2838, -123.1090],
    zoom: 16,
    description: 'Historic brick facades, vintage lampposts, Victorian Steam Clock, and acclaimed cocktail bars.',
    vibe: 'Brick Heritage, Speakeasy Cocktails & West Coast Cuisine',
    walkScore: 99,
    transitAccess: 'Waterfront SkyTrain Station (Expo, Millennium & Canada Lines)',
    pins: [
      {
        id: 'labattoir',
        name: 'L\'Abattoir',
        category: 'restaurant',
        lat: 49.2838,
        lng: -123.1090,
        address: '217 Carrall St',
        rating: 4.9,
        highlight: 'Refined French-influenced West Coast Fare in Refurbished 19th Century Butchery',
        actionText: 'Book Table on OpenTable',
        actionUrl: 'https://opentable.com/labattoir',
        hours: '5:00 PM - 10:00 PM',
        priceLevel: '$$$$',
      },
      {
        id: 'steam-clock',
        name: 'Gastown Steam Clock',
        category: 'attraction',
        lat: 49.2845,
        lng: -123.1089,
        address: '305 Water St',
        highlight: 'World-Famous Working 1977 Antique Steam Chime Clock',
        actionText: 'View Historic Guide',
        actionUrl: 'https://gastown.org',
        hours: 'Chimes every 15 minutes',
      },
    ],
  },
  {
    id: 'yvr-stanley-park',
    tenantId: 'yvr',
    keywords: ['stanley park', 'aquarium', 'seawall', 'prospect point', 'vancouver aquarium'],
    name: 'Stanley Park & Vancouver Aquarium',
    tagline: '400-Hectare Rainforest Oasis & Pacific Seawall',
    center: [49.3017, -123.1310],
    zoom: 15,
    description: 'World-renowned urban park surrounded by English Bay waters, cedar rainforest, and the famous 9km Seawall.',
    vibe: 'Pacific Coast Rainforest, Ocean Cycling & Marine Life',
    walkScore: 90,
    transitAccess: 'TransLink Bus 19 direct to Stanley Park Loop',
    pins: [
      {
        id: 'van-aquarium',
        name: 'Vancouver Aquarium (Ocean Wise)',
        category: 'attraction',
        lat: 49.3006,
        lng: -123.1312,
        address: '845 Avison Way (Stanley Park)',
        rating: 4.8,
        highlight: 'Rescued Sea Otters, Amazon Rainforest & Steller Sea Lions',
        actionText: 'Book Aquarium Tickets',
        actionUrl: 'https://vanaqua.org',
        hours: '10:00 AM - 5:00 PM Daily',
      },
      {
        id: 'prospect-point',
        name: 'Prospect Point Lookout',
        category: 'park',
        lat: 49.3142,
        lng: -123.1415,
        address: '5601 Stanley Park Dr',
        highlight: 'Spectacular Vistas of Lions Gate Bridge & Burrard Inlet',
        actionText: 'View Lookout Guide',
        actionUrl: 'https://vancouver.ca/parks-recreation-culture/stanley-park.aspx',
        hours: 'Open Dawn to Dusk',
      },
    ],
  },
];

export function findMatchingGeoSpotlight(
  query: string,
  tenantId: string
): GeoSpotlightDistrict | null {
  const normalized = query.toLowerCase();

  // First search strictly within the current tenant's spotlights
  const citySpotlights = CANADIAN_GEO_SPOTLIGHTS.filter(
    (s) => s.tenantId.toLowerCase() === tenantId.toLowerCase()
  );

  for (const district of citySpotlights) {
    for (const keyword of district.keywords) {
      if (normalized.includes(keyword)) {
        return district;
      }
    }
  }

  // Fallback: Check if any generic landmark matches
  for (const district of citySpotlights) {
    for (const pin of district.pins) {
      if (normalized.includes(pin.name.toLowerCase())) {
        return district;
      }
    }
  }

  return null;
}

export interface RooftopPatio {
  id: string;
  name: string;
  neighborhood: string;
  elevation: string;
  vibe: string;
  viewHighlight: string;
  signatureDrinkOrDish: string;
  heatedOrCovered: string;
  bookingUrl: string;
  bookingPlatform: string;
}

export interface SpeakeasyVenue {
  id: string;
  name: string;
  neighborhood: string;
  entranceSecret: string;
  vibe: string;
  specialty: string;
  hours: string;
  guestlistUrl: string;
}

export const ROOFTOP_PATIOS: Record<string, RooftopPatio[]> = {
  yyc: [
    {
      id: 'yyc-roof-1',
      name: 'Major Tom Bar',
      neighborhood: 'Downtown / Stephen Ave (40th Floor)',
      elevation: '40 Floors Up (Scotia Centre)',
      vibe: 'Canada’s #1 dining room and sunset cocktail sky lounge with retro-plush seating and 360° Rocky Mountain views',
      viewHighlight: 'Unobstructed 360° panorama of the Rocky Mountains, Bow River & Calgary skyline',
      signatureDrinkOrDish: 'Major Bellini & Prime Alberta Striploin with Crispy Potato Puffs',
      heatedOrCovered: 'Floor-to-ceiling glass sky room with climate control',
      bookingUrl: 'https://www.sevenrooms.com/reservations/majortombar',
      bookingPlatform: 'SevenRooms',
    },
    {
      id: 'yyc-roof-2',
      name: 'The Wilde on 27',
      neighborhood: 'Downtown / 5th Ave SW (27th Floor)',
      elevation: '27th Floor Rooftop (The Dorian Hotel)',
      vibe: 'Opulent rooftop sanctuary with open-air terrace, dramatic crystal chandeliers, and haute cocktail artistry',
      viewHighlight: 'Sweeping city lights and northern skyline vistas',
      signatureDrinkOrDish: 'Oscar Wilde Absinthe Drip & Seared Foie Gras',
      heatedOrCovered: 'Heated open-air terrace with fire tables & indoor glass lounge',
      bookingUrl: 'https://www.sevenrooms.com/reservations/thewilde',
      bookingPlatform: 'SevenRooms',
    },
    {
      id: 'yyc-roof-3',
      name: 'Charbar Rooftop at Simmons',
      neighborhood: 'East Village / Riverfront Walk',
      elevation: 'Riverfront Rooftop Deck (Historic Simmons Building)',
      vibe: 'Bustling summer open-air deck overlooking the Bow River with Argentine wood-fired parrilla grills',
      viewHighlight: 'Direct panoramic views of the Bow River, St. Patrick’s Island & pedestrian bridge',
      signatureDrinkOrDish: 'Wood-Fired Fugazza & Gaucho Ribeye with Chimichurri',
      heatedOrCovered: 'Open-air summer deck with wind screens & heaters',
      bookingUrl: 'https://www.opentable.com/r/charbar-calgary',
      bookingPlatform: 'OpenTable',
    },
    {
      id: 'yyc-roof-4',
      name: 'Free House Craft Beer Rooftop',
      neighborhood: 'Kensington / Kensington Cres NW',
      elevation: '2nd Floor Rooftop Patio',
      vibe: 'Sunny, energetic Kensington hub dedicated 100% to Alberta craft beer, natural wines & local comfort bites',
      viewHighlight: 'Vibrant Kensington village streetscape and downtown tower peaks',
      signatureDrinkOrDish: 'Alberta Microbrew Flights & Duck Fat Fried Chicken Bites',
      heatedOrCovered: 'Heated pergolas and umbrella shades',
      bookingUrl: 'https://www.opentable.com/r/free-house-calgary',
      bookingPlatform: 'OpenTable',
    },
    {
      id: 'yyc-roof-5',
      name: 'National on 10th Rooftop',
      neighborhood: 'Beltline / 10th Ave SW',
      elevation: 'Massive Multi-Tier Rooftop',
      vibe: 'Calgary’s largest downtown rooftop patio with ping pong, cornhole, DJ sound systems, and sun-soaked crowds',
      viewHighlight: 'Beltline high-rise corridor and urban sunset views',
      signatureDrinkOrDish: 'Craft Beer Pitchers & Smoked Brisket Sliders',
      heatedOrCovered: 'Heated canopies & fire tables for extended seasons',
      bookingUrl: 'https://ntnl.ca/national-10th',
      bookingPlatform: 'National Table Booking',
    },
    {
      id: 'yyc-roof-6',
      name: 'SKY 360 Revolving Restaurant',
      neighborhood: 'Downtown / Calgary Tower Base',
      elevation: '155 Meters Above Ground (Calgary Tower)',
      vibe: 'Revolving fine-dining salon rotating 360 degrees every 45 minutes for unbeatable Rockies and city views',
      viewHighlight: 'Complete 360° panorama of the entire Calgary metro region, foothills & Rocky Mountain peaks',
      signatureDrinkOrDish: 'Alberta Braised Short Rib & Truffle Frites',
      heatedOrCovered: 'Fully enclosed revolving panoramic sphere',
      bookingUrl: 'https://www.sky360.ca',
      bookingPlatform: 'OpenTable',
    },
  ],
  yyz: [
    {
      id: 'yyz-roof-1',
      name: 'Kost at Bisha Hotel',
      neighborhood: 'Entertainment District / Blue Jays Way',
      elevation: '44th Floor Rooftop & Infinity Pool',
      vibe: 'Baja-Californian luxury escape 44 stories above Toronto with infinity pool and CN Tower views',
      viewHighlight: 'Direct, jaw-dropping look at the CN Tower, Rogers Centre & Lake Ontario',
      signatureDrinkOrDish: 'Baja Ceviche, Coconut Rice & Watermelon Paloma',
      heatedOrCovered: 'Year-round glass conservatory and outdoor summer deck',
      bookingUrl: 'https://www.opentable.com/r/kost-toronto',
      bookingPlatform: 'OpenTable',
    },
    {
      id: 'yyz-roof-2',
      name: 'Harriet’s Rooftop at 1 Hotel',
      neighborhood: 'King West / Wellington St W',
      elevation: 'Open-Concept Eco-Luxury Rooftop',
      vibe: 'Sustainable luxury lounge with reclaimed timber, plush daybeds, master mixology, and high-energy DJ sets',
      viewHighlight: 'Uninterrupted King West skyline and downtown high-rise corridor',
      signatureDrinkOrDish: 'Japanese Robata Skewers & Sustainable Botanical Cocktails',
      heatedOrCovered: 'Retractable glass roof & heated outdoor terrace',
      bookingUrl: 'https://www.sevenrooms.com/reservations/harrietsrooftop',
      bookingPlatform: 'SevenRooms',
    },
    {
      id: 'yyz-roof-3',
      name: 'The Broadview Hotel Rooftop',
      neighborhood: 'Riverside / Queen St E',
      elevation: 'Historic 7th Floor Glass Tower Rooftop',
      vibe: 'Trendy east-side rooftop bar and terrace known for the city’s best sunset skyline views',
      viewHighlight: 'West-facing panorama of the entire downtown financial skyline across the Don Valley',
      signatureDrinkOrDish: 'Queen East Spritz & Crispy Pork Belly Bao',
      heatedOrCovered: 'Enclosed 360° glass atrium and heated outdoor deck',
      bookingUrl: 'https://www.opentable.com/r/the-rooftop-at-the-broadview-hotel-toronto',
      bookingPlatform: 'OpenTable',
    },
    {
      id: 'yyz-roof-4',
      name: 'Lavelle',
      neighborhood: 'King West / King St W',
      elevation: '16-Storey Expansive Rooftop Oasis',
      vibe: '16,000 sq ft playground with 3 outdoor plunge pools, cabanas, French dining, and late-night nightlife',
      viewHighlight: '360° unobstructed city views including CN Tower and Lake Ontario',
      signatureDrinkOrDish: 'Steak Frites, Tuna Tartare & King West Sunset Cocktails',
      heatedOrCovered: 'Heated dining enclosure and open-air pool deck',
      bookingUrl: 'https://www.sevenrooms.com/reservations/lavelle',
      bookingPlatform: 'SevenRooms',
    },
    {
      id: 'yyz-roof-5',
      name: 'The Drake Sky Yard',
      neighborhood: 'West Queen West',
      elevation: 'Artistic Boutique Rooftop Deck',
      vibe: 'Internationally famous climate-controlled artist rooftop with rotating murals, craft margaritas & brunch',
      viewHighlight: 'Queen West arts district streetscape and skyline silhouette',
      signatureDrinkOrDish: 'Drake Burger, Fish Tacos & Sky Yard Margarita',
      heatedOrCovered: '4-season all-weather covered canopy with heaters & fire pits',
      bookingUrl: 'https://www.thedrake.ca',
      bookingPlatform: 'OpenTable',
    },
  ],
  yvr: [
    {
      id: 'yvr-roof-1',
      name: 'Parker Rooftop',
      neighborhood: 'Downtown South / Howe St',
      elevation: '120 Feet Above Ground (Parker Hotel)',
      vibe: 'Glamorous multi-patio rooftop with 20-foot ceilings, fire tables, craft cocktails, and Spanish tapas',
      viewHighlight: '360° views of False Creek, English Bay sunsets & North Shore mountains',
      signatureDrinkOrDish: 'Spanish Jamón Croquetas & Golden Hour Mezcal Spritz',
      heatedOrCovered: 'Three distinct heated and covered outdoor terraces',
      bookingUrl: 'https://www.sevenrooms.com/reservations/parkerrooftop',
      bookingPlatform: 'SevenRooms',
    },
    {
      id: 'yvr-roof-2',
      name: 'Reflections: The Garden Terrace',
      neighborhood: 'Downtown / Rosewood Hotel Georgia',
      elevation: '4th Floor Inner Courtyard Rooftop',
      vibe: 'Lush botanical sanctuary with elegant cabanas, whispering waterfalls, and light tapas dining',
      viewHighlight: 'Intimate urban garden framed by heritage architecture',
      signatureDrinkOrDish: 'Truffle Parmesan Fries & Georgia Peach Bellini',
      heatedOrCovered: 'Heated winter garden enclosure & summer open-air terrace',
      bookingUrl: 'https://www.opentable.com/r/reflections-the-garden-terrace-vancouver',
      bookingPlatform: 'OpenTable',
    },
    {
      id: 'yvr-roof-3',
      name: 'The Roof at Black+Blue',
      neighborhood: 'Alberni Street Luxury Row',
      elevation: '3rd Floor Rooftop Steakhouse',
      vibe: 'Vancouver’s premier rooftop steakhouse featuring Josper charcoal wood-fired grills and plush booths',
      viewHighlight: 'Downtown architectural canyon and Alberni luxury district',
      signatureDrinkOrDish: 'Kobe Beef Skewers & Smoked Bourbon Old Fashioned',
      heatedOrCovered: 'Fully heated with state-of-the-art retractable glass roof',
      bookingUrl: 'https://www.opentable.com/r/the-roof-at-black-and-blue-vancouver',
      bookingPlatform: 'OpenTable',
    },
    {
      id: 'yvr-roof-4',
      name: 'The Keg Steakhouse + Bar Rooftop',
      neighborhood: 'Yaletown / Mainland St',
      elevation: 'Multi-Level Heritage Brick Rooftop',
      vibe: 'Massive 4-season rooftop patio with roaring outdoor fireplaces, lounge seating, and electric Yaletown buzz',
      viewHighlight: 'Historic Yaletown loading docks and illuminated brick streets',
      signatureDrinkOrDish: 'Prime Rib Sliders & Keg Classic Martinis',
      heatedOrCovered: 'Heated year-round with massive central fire features',
      bookingUrl: 'https://www.opentable.com/r/the-keg-steakhouse-and-bar-yaletown-vancouver',
      bookingPlatform: 'OpenTable',
    },
  ],
  yul: [
    {
      id: 'yul-roof-1',
      name: 'Terrasse Nelligan',
      neighborhood: 'Old Montreal / Rue Saint-Paul O',
      elevation: '4th Floor Historic Rooftop (Hôtel Nelligan)',
      vibe: 'Old Port’s most celebrated rooftop terrace overlooking 300-year-old historic stone architecture',
      viewHighlight: 'Notre-Dame Basilica towers, St. Lawrence River & Old Montreal rooftops',
      signatureDrinkOrDish: 'Clear Sangria Pitchers & Quebec Artisan Charcuterie Boards',
      heatedOrCovered: 'Equipped with retractable awnings and powerful outdoor heaters',
      bookingUrl: 'https://www.opentable.com/r/terrasse-nelligan-montreal',
      bookingPlatform: 'OpenTable',
    },
    {
      id: 'yul-roof-2',
      name: 'Terrasse Place d’Armes',
      neighborhood: 'Old Montreal / Côte de la Place d’Armes',
      elevation: '8th Floor Rooftop Vantage',
      vibe: 'Chic urban terrace perched directly above Montreal’s most famous historical square',
      viewHighlight: 'Direct look onto Place d’Armes, Saint-Jacques financial facades & downtown towers',
      signatureDrinkOrDish: 'Famous Raspberry Mojito & Duck Confit Dumplings',
      heatedOrCovered: 'Partially covered with heated lounge seating',
      bookingUrl: 'https://www.opentable.com/r/terrasse-place-darmes-montreal',
      bookingPlatform: 'OpenTable',
    },
    {
      id: 'yul-roof-3',
      name: 'Terrasse Carla',
      neighborhood: 'Chinatown / Boul Saint-Laurent',
      elevation: '6th Floor Rooftop (Hampton by Hilton)',
      vibe: 'French-Vietnamese tropical rooftop lounge with lush neon foliage, guest DJs, and vibrant sunset cocktails',
      viewHighlight: 'Skyline sunset vistas across Quartier des Spectacles',
      signatureDrinkOrDish: 'Saigon Spring Rolls, Lemongrass Chicken Skewers & Lychee Martini',
      heatedOrCovered: 'Fully heated outdoor covered terrace',
      bookingUrl: 'https://www.sevenrooms.com/reservations/terrassecarla',
      bookingPlatform: 'SevenRooms',
    },
  ],
  yeg: [
    {
      id: 'yeg-roof-1',
      name: 'The Confederation Lounge Patio',
      neighborhood: 'Downtown / Fairmont Hotel Macdonald',
      elevation: 'Perched on the River Valley Edge',
      vibe: 'The undisputed grand terrace of Edmonton, looking out over North America’s largest urban parkland',
      viewHighlight: '180° breathtaking panorama of the North Saskatchewan River Valley and Walterdale Bridge',
      signatureDrinkOrDish: 'Macdonald Charcuterie, Alberta Prime Rib & House Old Fashioned',
      heatedOrCovered: 'Heated fire tables with blankets and sun umbrellas',
      bookingUrl: 'https://www.opentable.com/r/the-confederation-lounge-edmonton',
      bookingPlatform: 'OpenTable',
    },
    {
      id: 'yeg-roof-2',
      name: 'CRAFT Beer Market Rooftop',
      neighborhood: 'Downtown / Rice Howard Way',
      elevation: 'Expansive Multi-Tier Rooftop',
      vibe: 'Massive open-air beer garden with turf flooring, bocce ball, 100+ craft beer taps, and lively downtown energy',
      viewHighlight: 'Rice Howard Way pedestrian corridor and downtown skyscrapers',
      signatureDrinkOrDish: '100+ Canadian Craft Taps & Baja Fish Tacos',
      heatedOrCovered: 'Heated cabana booths & weather-proof awnings',
      bookingUrl: 'https://www.opentable.com/r/craft-beer-market-edmonton',
      bookingPlatform: 'OpenTable',
    },
  ],
  yow: [
    {
      id: 'yow-roof-1',
      name: 'Copper Spirits & Sights',
      neighborhood: 'ByWard Market / Andaz Hotel',
      elevation: '16th Floor (Tallest Rooftop in Ottawa)',
      vibe: 'Sleek luxury sky lounge with fire pits, Canadian spirits, and 360° vistas of the nation’s capital',
      viewHighlight: 'Spectacular sunset views over Parliament Hill, Ottawa River & Gatineau Hills',
      signatureDrinkOrDish: 'Canadian Maple Whisky Sours & Charcuterie from ByWard Market',
      heatedOrCovered: 'Heated outdoor observation terrace & indoor glass lounge',
      bookingUrl: 'https://www.opentable.com/r/copper-spirits-and-sights-ottawa',
      bookingPlatform: 'OpenTable',
    },
    {
      id: 'yow-roof-2',
      name: 'Tavern on the Hill',
      neighborhood: 'Major’s Hill Park / Mackenzie Ave',
      elevation: 'Major’s Hill Parkland Lookout',
      vibe: 'Open-air summer oasis with gourmet street tacos, local craft beers, and the best sunset terrace in Ottawa',
      viewHighlight: 'Direct view of Parliament Buildings, Supreme Court & the Ottawa River',
      signatureDrinkOrDish: 'Artisanal Gourmet Hot Dogs, Baja Tacos & Ottawa Craft Cider',
      heatedOrCovered: 'Outdoor parkland patio with shaded umbrellas and evening lighting',
      bookingUrl: 'https://www.tavernonthehill.ca',
      bookingPlatform: 'Official Website',
    },
  ],
  ywg: [
    {
      id: 'ywg-roof-1',
      name: 'Tavern United Rooftop',
      neighborhood: 'Downtown / Hargrave St',
      elevation: 'Multi-Tier Sports Rooftop',
      vibe: 'High-energy rooftop directly opposite Canada Life Centre with roaring fire pits and game-day crowds',
      viewHighlight: 'Downtown Winnipeg entertainment district and arena towers',
      signatureDrinkOrDish: 'Winnipeg Craft Pints & Loaded Game-Day Nachos',
      heatedOrCovered: 'Fire tables and glass windbreaks for crisp Prairie evenings',
      bookingUrl: 'https://tavernunited.com',
      bookingPlatform: 'Official Website',
    },
  ],
  yhz: [
    {
      id: 'yhz-roof-1',
      name: 'The Cable Wharf Waterfront Deck',
      neighborhood: 'Downtown / Lower Water St',
      elevation: 'Perched Right Over Halifax Harbour',
      vibe: 'Spectacular waterfront dining deck surrounded on three sides by ocean waves, sea breezes, and ship traffic',
      viewHighlight: 'Halifax Harbour, George’s Island & passing tall ships',
      signatureDrinkOrDish: 'Fresh Atlantic Lobster Rolls & East Coast Maritime Oysters',
      heatedOrCovered: 'Spacious heated waterfront deck with panoramic glass windows',
      bookingUrl: 'https://www.opentable.com/r/cable-wharf-kitchen-and-drinks-halifax',
      bookingPlatform: 'OpenTable',
    },
    {
      id: 'yhz-roof-2',
      name: 'The Bicycle Thief Patio',
      neighborhood: 'Bishop’s Landing / Lower Water St',
      elevation: 'Harbourfront Terrace & Fire Pit Lounge',
      vibe: 'Halifax’s most beloved luxury waterfront dining room with champagne cocktails and Italian-Canadian fare',
      viewHighlight: 'Halifax Harbour boardwalk and Bishop’s Landing marina',
      signatureDrinkOrDish: 'Spaghettini ai Frutti di Mare & House Bellini',
      heatedOrCovered: 'Heated fire pit tables and cozy blankets',
      bookingUrl: 'https://www.opentable.com/r/the-bicycle-thief-halifax',
      bookingPlatform: 'OpenTable',
    },
  ],
  yyj: [
    {
      id: 'yyj-roof-1',
      name: 'Vista 18 Restaurant + Lounge',
      neighborhood: 'Downtown / Chateau Victoria',
      elevation: '18th Floor Rooftop (Highest in Victoria)',
      vibe: 'Top-floor culinary lounge with West Coast seafood, craft wine lists, and sweeping Pacific panoramas',
      viewHighlight: 'Pacific Ocean, Juan de Fuca Strait, Olympic Mountains & BC Parliament Buildings',
      signatureDrinkOrDish: 'Pacific Halibut, Foraged Mushroom Risotto & Vancouver Island Pinots',
      heatedOrCovered: 'Climate-controlled panoramic dining room & observation lounge',
      bookingUrl: 'https://www.opentable.com/r/vista-18-westcoast-grill-and-wine-bar-victoria',
      bookingPlatform: 'OpenTable',
    },
    {
      id: 'yyj-roof-2',
      name: 'LURE Restaurant & Bar Patio',
      neighborhood: 'Inner Harbour / Harbour Rd',
      elevation: 'Harbourfront Waterfront Terrace',
      vibe: 'Victoria’s premier heated waterfront patio with modern fire features, local bites, and sparkling marina views',
      viewHighlight: 'Inner Harbour, BC Parliament lighting, and floatplanes taking off',
      signatureDrinkOrDish: 'Island Seafood Chowder & Vancouver Island Craft IPAs',
      heatedOrCovered: 'Fully heated outdoor patio with fire pits for year-round comfort',
      bookingUrl: 'https://www.opentable.com/r/lure-restaurant-and-bar-victoria',
      bookingPlatform: 'OpenTable',
    },
  ],
  yyt: [
    {
      id: 'yyt-roof-1',
      name: 'Quidi Vidi Brewing Company Wharf Deck',
      neighborhood: 'Quidi Vidi Village / Barrows Rd',
      elevation: 'Historic Ocean Gut Wharf',
      vibe: 'Unforgettable seaside deck resting right above the water in a 400-year-old historic fishing village',
      viewHighlight: 'Quidi Vidi gut, sheer rocky cliffs, and traditional fishing stages',
      signatureDrinkOrDish: 'Iceberg Beer (brewed with 20,000-year-old glacial water) & Fresh Cod Tacos',
      heatedOrCovered: 'Open-air ocean wharf deck with cozy taproom inside',
      bookingUrl: 'https://quidividibrewery.ca',
      bookingPlatform: 'Official Website',
    },
  ],
};

export const SPEAKEASIES: Record<string, SpeakeasyVenue[]> = {
  yyc: [
    {
      id: 'yyc-spk-1',
      name: 'Sub Rosa',
      neighborhood: 'Downtown (Under Hudson’s Bay Building, 200 8th Ave SW)',
      entranceSecret: 'Descend an unassuming subterranean stairway into a 100-year-old heritage brick vault',
      vibe: 'Subterranean luxury sanctuary with plush velvet booths, historic brick arches, and weekend guest DJs',
      specialty: 'Smoked Old Fashioneds, bespoke gin elixirs & premium table bottle service',
      hours: 'Thu - Sat • 8:00 PM - 2:00 AM',
      guestlistUrl: 'https://subrosayyc.com',
    },
    {
      id: 'yyc-spk-2',
      name: 'Betty Lou’s Library',
      neighborhood: 'Beltline / 17th Ave SW (908 17th Ave SW)',
      entranceSecret: 'Locate the hidden bookcase door; pick up the vintage rotary phone and whisper the daily secret password',
      vibe: 'Authentic 1920s Prohibition speakeasy with jazz vinyls, antique armchairs, and flapper-era cocktail glamour',
      specialty: 'Literary-themed cocktails (The Virginia Woolf, The Great Gatsby) with house-made tinctures',
      hours: 'Wed - Sun • 5:00 PM - 1:00 AM',
      guestlistUrl: 'https://bettylouslibrary.com',
    },
    {
      id: 'yyc-spk-3',
      name: 'Untitled Champagne Lounge',
      neighborhood: 'Downtown / 8th Ave SE',
      entranceSecret: 'Discreet, unlabelled entrance on 8th Ave opening into a velvet-draped champagne salon',
      vibe: 'Dimly-lit opulent lounge dedicated to grower Champagnes, artisan sparkling wines, and caviar service',
      specialty: 'Rare vintage Champagnes, French sparkling flights & bespoke vodka cocktails',
      hours: 'Thu - Sat • 6:00 PM - 1:00 AM',
      guestlistUrl: 'https://untitledyyc.com',
    },
    {
      id: 'yyc-spk-4',
      name: 'Paper Lantern',
      neighborhood: 'Chinatown Basement (241 1st St SE)',
      entranceSecret: 'Walk down an unmarked basement staircase in Chinatown into a glowing neon Vietnamese speakeasy',
      vibe: 'Intimate, moody tropical cellar with lantern lighting, Vietnamese bites, and playful tropical mixology',
      specialty: 'Pandan cocktails, Vietnamese spiced rum punches & Bánh Mì sliders',
      hours: 'Tue - Sat • 5:00 PM - 12:00 AM',
      guestlistUrl: 'https://www.instagram.com/paperlanternyyc',
    },
    {
      id: 'yyc-spk-5',
      name: 'Frenchie Wine Bar',
      neighborhood: 'Beltline / Behind Pizzaface (17th Ave SW)',
      entranceSecret: 'Walk through the pizzeria to the back closet door to find a hidden 15-seat French wine haven',
      vibe: 'Secret backroom hideaway with curated natural wines, artisanal cheeses, and molten raclette fondue',
      specialty: 'Natural low-intervention French wines & Alpine cheese boards',
      hours: 'Thu - Sun • 6:00 PM - Late',
      guestlistUrl: 'https://www.frenchieyyc.com',
    },
  ],
  yyz: [
    {
      id: 'yyz-spk-1',
      name: 'Mahjong Bar',
      neighborhood: 'Little Portugal / 1276 Dundas St W',
      entranceSecret: 'Step through a functioning, tiny 1970s pink Chinese bodega storefront into a secret 2,000 sq ft cocktail hall',
      vibe: 'Stunning glowing mural ceiling, craft cocktails, Shanghai street snacks, and late-night weekend DJs',
      specialty: 'Trophy Wife cocktail, Sichuan fried chicken & curated baijiu drinks',
      hours: 'Wed - Sun • 5:00 PM - 2:00 AM',
      guestlistUrl: 'https://mahjongbar.com',
    },
    {
      id: 'yyz-spk-2',
      name: 'Gift Shop',
      neighborhood: 'Ossington Ave / 89-B Ossington',
      entranceSecret: 'Hidden directly behind a functioning barbershop chair; push the secret mirror door to enter',
      vibe: 'Intimate 20-seat bespoke cocktail salon run by master bartenders tailoring drinks to your palate',
      specialty: 'Custom bespoke mixology, clarified punches & vintage spirits',
      hours: 'Daily • 6:00 PM - 2:00 AM',
      guestlistUrl: 'https://www.instagram.com/giftshopto',
    },
    {
      id: 'yyz-spk-3',
      name: 'Vatican Giftshop',
      neighborhood: 'Leslieville / 1047 Gerrard St E',
      entranceSecret: 'Walk through a kitschy religious artifact and rosary store to enter an energetic cocktail hall & pizza joint',
      vibe: 'High-energy East End party tavern with neon crucifixes, wood-fired Neapolitan pies, and craft beers',
      specialty: 'Holy Water cocktails, artisanal pizza & local live music sets',
      hours: 'Wed - Sun • 5:00 PM - 2:00 AM',
      guestlistUrl: 'https://vaticangiftshop.com',
    },
    {
      id: 'yyz-spk-4',
      name: 'Cry Baby Gallery',
      neighborhood: 'Dundas West / 1468 Dundas St W',
      entranceSecret: 'Enter through a functioning contemporary art gallery into a hidden Prohibition cocktail parlor behind the back wall',
      vibe: 'Moody, candlelit speakeasy with oyster shucking, inventive house cocktails, and low-key hip-hop beats',
      specialty: 'Fresh East Coast oysters, smoky mezcal cocktails & house negronis',
      hours: 'Daily • 5:00 PM - 2:00 AM',
      guestlistUrl: 'https://crybabygallery.ca',
    },
  ],
  yvr: [
    {
      id: 'yvr-spk-1',
      name: 'Key Party',
      neighborhood: 'Mount Pleasant / 2303 Main St',
      entranceSecret: 'Step into "Zac’s Accounting Office" on Main St; open the back accounting door to reveal the 1970s parlor',
      vibe: 'Retro 1970s velvet-draped cocktail den with macramé, red velvet booths, and nostalgic fondue',
      specialty: 'Cherry Cola Highballs, Grasshoppers & Warm Cheese Fondue',
      hours: 'Daily • 5:00 PM - 1:00 AM',
      guestlistUrl: 'https://keyparty.ca',
    },
    {
      id: 'yvr-spk-2',
      name: 'Bagheera',
      neighborhood: 'Chinatown / 518 Main St',
      entranceSecret: 'Walk into "Happy Valley Crossbow Co.", ring the brass counter bell and state your name to open the secret passage',
      vibe: 'Opulent 1800s Indian subcontinent railway carriage lounge with 42-foot hand-painted murals and luxury booths',
      specialty: 'Saffron-infused gin cocktails, subcontinent street snacks & royal punch bowls',
      hours: 'Daily • 5:00 PM - 1:00 AM',
      guestlistUrl: 'https://bagheera.bar',
    },
    {
      id: 'yvr-spk-3',
      name: 'The Narrow Lounge',
      neighborhood: 'Mount Pleasant / Main & 3rd Ave',
      entranceSecret: 'Marked only by a single red light over an unmarked doorway; walk down the graffiti-lined hallway',
      vibe: 'Ultra-intimate dimly lit dive-speakeasy with craft pints, cocktail pitchers, and hidden back patio',
      specialty: 'Spicy margaritas, artisan grilled cheese & local BC craft beers',
      hours: 'Daily • 4:00 PM - Late',
      guestlistUrl: 'https://narrowlounge.com',
    },
  ],
  yul: [
    {
      id: 'yul-spk-1',
      name: 'The Coldroom',
      neighborhood: 'Old Montreal / Rue Saint-Vincent',
      entranceSecret: 'Find the nondescript black metal door with a small yellow rubber duck sticker; press the buzzer for entry',
      vibe: 'Subterranean 1800s cold storage vault transformed into one of North America’s premier cocktail institutions',
      specialty: 'Montreal Sour, tailored mixology & rare bespoke amaros',
      hours: 'Daily • 5:00 PM - 3:00 AM',
      guestlistUrl: 'https://thecoldroommtl.com',
    },
    {
      id: 'yul-spk-2',
      name: 'Cloakroom Bar',
      neighborhood: 'Golden Square Mile / Rue de la Montagne',
      entranceSecret: 'Step inside a luxury bespoke menswear boutique; open the hidden mirrored wall at the rear',
      vibe: 'Ultra-exclusive 25-seat dark wood sanctuary with no cocktail menu — master mixologists craft each drink to order',
      specialty: 'Hand-carved artisanal ice crystals & bespoke spirit pairings tailored to your exact taste profile',
      hours: 'Daily • 3:00 PM - 3:00 AM',
      guestlistUrl: 'https://cloakroombar.com',
    },
    {
      id: 'yul-spk-3',
      name: 'Soubois',
      neighborhood: 'Downtown / Boul de Maisonneuve O',
      entranceSecret: 'Descend an unmarked underground stairwell into an illuminated underground boreal forest',
      vibe: 'Enchanted subterranean supper club and nightclub with wooden canopy carvings, raw bar, and DJ dance floors',
      specialty: 'Yellowfin tuna tartare, caviar service & VIP bottle service',
      hours: 'Thu - Sat • 6:00 PM - 3:00 AM',
      guestlistUrl: 'https://soubois.com',
    },
  ],
  yeg: [
    {
      id: 'yeg-spk-1',
      name: 'Fu’s Repair Shop',
      neighborhood: 'Whyte Ave / 10524 82 Ave NW',
      entranceSecret: 'Disguised as a vintage electronics repair shop; enter through the retro front to find the neon dining hall',
      vibe: 'High-energy neon dim sum lounge with hip hop playlists, creative Asian cocktails, and late-night vibes',
      specialty: 'Fu’s House Punch, Dan Dan Noodles & Pork Belly Bao',
      hours: 'Wed - Sun • 5:00 PM - Late',
      guestlistUrl: 'https://fusrepairshop.ca',
    },
    {
      id: 'yeg-spk-2',
      name: 'Bar Clementine',
      neighborhood: 'Oliver / 11957 Jasper Ave',
      entranceSecret: 'Tucked away on Jasper Ave, entered through an unassuming art nouveau wood-carved portal',
      vibe: 'Early 20th-century French salon with hand-hewn woodwork, botanical infusions, and exquisite small plates',
      specialty: 'Botanical French cocktails, absinthe fountains & local charcuterie',
      hours: 'Tue - Sat • 5:00 PM - 11:00 PM',
      guestlistUrl: 'https://barclementine.ca',
    },
  ],
  yow: [
    {
      id: 'yow-spk-1',
      name: 'Union Local 613 (Speakeasy Cellar)',
      neighborhood: 'Centretown / 315 Somerset St W',
      entranceSecret: 'Head downstairs toward the basement coat check and push open the secret wooden bookcase',
      vibe: 'Intimate subterranean speakeasy with tin ceilings, bespoke bourbon cocktails, and southern comfort food',
      specialty: 'Smoked bourbon old fashioneds, fried green tomatoes & raw bar oysters',
      hours: 'Wed - Sun • 5:00 PM - 2:00 AM',
      guestlistUrl: 'https://union613.ca',
    },
    {
      id: 'yow-spk-2',
      name: 'The Moonroom',
      neighborhood: 'Little Italy / 442 Preston St',
      entranceSecret: 'Unmarked, dimly candlelit storefront on Preston Street with curtained windows',
      vibe: 'Romantic, bohemian cocktail sanctuary with glowing candles, vintage mirrors, and artisan Italian charcuterie',
      specialty: 'House-infused herbal elixirs, prosecco cocktails & warm focaccia boards',
      hours: 'Daily • 5:00 PM - 2:00 AM',
      guestlistUrl: 'https://themoonroom.ca',
    },
  ],
  ywg: [
    {
      id: 'ywg-spk-1',
      name: 'Patent 5 Distillery & Tasting Vault',
      neighborhood: 'Exchange District / 108 Alexander Ave',
      entranceSecret: 'Located inside a historic 1900s stable building with antique oak doors and stained glass',
      vibe: 'Grand heritage distillery tasting room with reclaimed oak bar, velvet armchairs, and craft spirits',
      specialty: 'Patent 5 Artisan Gin Martinis & Manitoba Botanical cocktails',
      hours: 'Wed - Sun • 4:00 PM - 11:00 PM',
      guestlistUrl: 'https://patent5.ca',
    },
    {
      id: 'ywg-spk-2',
      name: 'Langside Grocery',
      neighborhood: 'West Broadway / 164 Langside St',
      entranceSecret: '100-year-old neighborhood corner grocery facade hiding an intimate European cocktail salon',
      vibe: 'Romantic, candlelit neighborhood gem with French bistro marble tables and bespoke mixology',
      specialty: 'Classic French 75s, negroni variations & artisanal cheese plates',
      hours: 'Daily • 5:00 PM - Late',
      guestlistUrl: 'https://langsidegrocery.com',
    },
  ],
  yhz: [
    {
      id: 'yhz-spk-1',
      name: 'Noble Speakeasy',
      neighborhood: 'Downtown / Beneath The Middle Spoon (1563 Barrington St)',
      entranceSecret: 'Ask your server at The Middle Spoon for the secret weekly password; get escorted through the basement vault door',
      vibe: 'Clandestine subterranean brick-and-stone cocktail cellar with antique velvet furnishings and jazz vibes',
      specialty: 'Noble House Bourbon infusions, smoked cocktails & dessert pairings',
      hours: 'Thu - Sat • 7:00 PM - 2:00 AM',
      guestlistUrl: 'https://themiddlespoon.com/noble',
    },
    {
      id: 'yhz-spk-2',
      name: 'The Highwayman',
      neighborhood: 'Downtown / 1673 Barrington St',
      entranceSecret: 'Discreet dark wood storefront on Barrington opening into an authentic Spanish pintxos haven',
      vibe: 'Intimate Spanish tavern with leather booths, world-class sherry cocktails, and fresh Nova Scotia seafood',
      specialty: 'Sherry & mezcal cocktails, Galician octopus & jamón ibérico',
      hours: 'Daily • 4:00 PM - 12:00 AM',
      guestlistUrl: 'https://highwaymanhfx.com',
    },
  ],
  yyj: [
    {
      id: 'yyj-spk-1',
      name: 'Clive’s Classic Lounge',
      neighborhood: 'Downtown / 740 Burdett Ave',
      entranceSecret: 'Tucked into the ground floor of Chateau Victoria with discreet wood-paneled entrance',
      vibe: 'Canada’s longest-running international award-winning cocktail bar with leather armchairs and master mixologists',
      specialty: 'Bespoke vintage cocktail flights, house barrel-aged spirits & Pacific Northwest bites',
      hours: 'Daily • 5:00 PM - 12:00 AM',
      guestlistUrl: 'https://clivesclassiclounge.com',
    },
    {
      id: 'yyj-spk-2',
      name: 'Citrus & Cane',
      neighborhood: 'Downtown / 1900 Douglas St',
      entranceSecret: 'Unassuming Douglas Street entrance opening into an extravagant 1970s tropical palace',
      vibe: 'Retro tropical cocktail lounge with velvet palm booths, terrazzo floors, and tiki mixology artistry',
      specialty: 'Mai Tai variations, clarified rum punches & tropical cocktails',
      hours: 'Wed - Sun • 5:00 PM - Late',
      guestlistUrl: 'https://citrusandcane.com',
    },
  ],
  yyt: [
    {
      id: 'yyt-spk-1',
      name: 'Underbelly at YellowBelly Brewery',
      neighborhood: 'Downtown / 288 Water St',
      entranceSecret: 'Descend to the 1846 stone masonry cellar beneath Newfoundland’s historic public house',
      vibe: 'Historic stone-walled underground speakeasy with barrel vaults, single-cask ales, and craft cocktails',
      specialty: 'Single-cask local ales, Newfoundland Screech cocktails & wood-fired flatbreads',
      hours: 'Thu - Sat • 6:00 PM - 2:00 AM',
      guestlistUrl: 'https://yellowbellybrewery.com',
    },
    {
      id: 'yyt-spk-2',
      name: 'The Ship Pub',
      neighborhood: 'Downtown / 265 Duckworth St',
      entranceSecret: 'Walk down the historic Solomon’s Lane alleyway into the legendary subterranean arts institution',
      vibe: 'Beloved underground meeting place for musicians, artists, and locals with live traditional tunes',
      specialty: 'Fresh Atlantic fish and chips, local craft pints & authentic Newfoundland hospitality',
      hours: 'Daily • 4:00 PM - Late',
      guestlistUrl: 'https://theshippub.com',
    },
  ],
};

